volumes:
  centreon-share:
    name: centreon-share
  centreon-img:
    name: centreon-img


networks:
  centreon_net:
    name: centreon_net
    ipam:
      driver: default
      config:
        - subnet: "172.26.0.0/24"


services:
  apache:
    build:
      context: http
      args:
        - TZ=${TZ}
    image: tpo76/apache:24.04.0
    env_file:
      - .env
    container_name: apache
    hostname: apache
    restart: always
    networks:
      - centreon_net
    ports:
      - 80:80
    volumes:
      - centreon-share:/usr/share/centreon:rw
      - centreon-img:/usr/share/centreon/www/img/media:rw